import { Typography } from 'antd';
import Head from 'next/head';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Typography.Title>Department of Computer Science</Typography.Title>

        <div>
          <Typography.Text>
            Jamia Millia Islamia was founded at Aligarh in the United Province,
            India in 1920 during the Khilafat and Non-Cooperation Movement in
            response to Gandhiji&apos;s call to boycott government supported
            educational institutions. JMI moved from Aligarh to Delhi in the
            year 1925 and was made a central university by Parliamentary act of
            1988. Today, Jamia Millia Islamia is one of the most prominent and
            promising central university of the country. JMI was recently
            awarded an &lsquo;A&rsquo; Grade by NAAC (National Assessment and
            Accreditation Council).
          </Typography.Text>
        </div>

        <div>
          <Typography.Title level={3}>How to reach us</Typography.Title>
          <Typography.Text>
            Jamia Millia Islamia is located on the south-east corner of Delhi,
            near various beautiful places such as Lodhi Garden, Chattarpur
            Mandir and Lotus Temple. One may reach the University by road or by
            metro, It is well-connected and may take any of the following routes
            to reach it
          </Typography.Text>
        </div>

        <div>
          <Typography.Title level={4}>
            New Delhi Railway Station
          </Typography.Title>
          <Typography.Text>
            It takes just under an hour to travel the 13.3 km between the
            station and the University, via Mathura road. Buses, Cabs, auto
            rickshaws, etc. are the various modes from which one may choose to
            cover the distance, if there is no private vehicles available at
            disposal.
          </Typography.Text>
        </div>

        <div>
          <Typography.Title level={4}>
            INDIRA GANDHI INTERNATIONAL AIRPORT
          </Typography.Title>
          <Typography.Text>
            The 19 kilometers between the airport and University usually
            requires an hour to commute via road.
          </Typography.Text>
        </div>

        <div>
          <Typography.Title level={4}>METRO</Typography.Title>
          <Typography.Text>
            Nearest metro stations are &lsquo;Jamia Millia Islamia&rsquo; and
            &lsquo;Sukhdev Vihar&rsquo;, on magenta line, which are at walking
            distance from the University.
          </Typography.Text>
        </div>

        <div>
          <Typography.Title level={4}> BUS STATION</Typography.Title>
          <Typography.Text>
            There are numerous bus stops near the University that help enhance
            the connectivity between Jamia and the rest of the city.
          </Typography.Text>
        </div>
      </main>
    </>
  );
};

export default Home;
